GET http://localhost:3001/

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6322a3f701be97503778d6f9

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "dkfffjhfdf",
    "number": "10-22-334455"
}

###

PUT http://localhost:3001/api/persons/6322a3f701be97503778d6f9
Content-Type: application/json

{
    "number": "new number"
}